### ISSUE TITLE
Suggestion: Windows Taskbar progress

### ISSUE THREAD

**Issue by ashmind** [Mpdreamz/shellprogressbar#1]
I think it would be cool if this library optionally displayed the progress in Windows Taskbar.

This can be done through `TaskbarManager` from Windows API Code Pack, or by p/invoking WinAPI directly. Console window handle can be obtained from

```
[DllImport("kernel32.dll", SetLastError = true)]
private static extern IntPtr GetConsoleWindow();
```

Unfortunately I do not have time to do a proper implementation/pull request at the moment, so just an idea.

**Comment by Mpdreamz** [comment]
Awesome Idea :+1: , will see if I can find some cycles this weekend.
