### ISSUE TITLE
Dependency on System.Text.Encoding.CodePages

### ISSUE THREAD

**Issue by thoemmi** [Mpdreamz/shellprogressbar#16]
Currently **ShellProgressBar** has a [dependency](https://github.com/Mpdreamz/shellprogressbar/blob/d0481de8141016a03c7d58403633cedc01cf907f/src/ShellProgressBar/ShellProgressBar.csproj#L18) on [System.Text.Encoding.CodePages](https://www.nuget.org/packages/System.Text.Encoding.CodePages/). However, I cannot see any reference to that package except in [**ShellProgressBar.Example**](https://github.com/Mpdreamz/shellprogressbar/blob/00eaf96f7209be95e01ba07cb996db4d5c4b00f2/src/ShellProgressBar.Example/Program.cs#L40). Is the dependency really required?

**Comment by Mpdreamz** [comment]
https://github.com/Mpdreamz/shellprogressbar/blob/d0481de8141016a03c7d58403633cedc01cf907f/src/ShellProgressBar/ProgressBarBase.cs#L12 uses it as well to make sure UTF-8 characters are printed correctly on codepages .NET core does not know about OOTB. 

Is this dependency causing any issues?

**Comment by thoemmi** [comment]
Oh, for whatever reason I missed that line. Sorry for bothering you.

**Comment by Mpdreamz** [comment]
No bother!
