### ISSUE TITLE
Child progress bars not working in powershell

### ISSUE THREAD

**Issue by rookboom** [Mpdreamz/shellprogressbar#19]
Child progress bars do not render correctly in powershell  or in the VS Code terminal. All the children write over the root progressbar instead of being stacked on top of each other.

I seems to only display correctly in the Windows command shell.

My options are set to : ```
            ProgressBarOptions(
                                             ForegroundColor = ConsoleColor.Yellow,
                                             ForegroundColorDone = Nullable<_>(ConsoleColor.DarkGreen),
                                             BackgroundColor = Nullable<_>(ConsoleColor.DarkGray),
                                             BackgroundCharacter = Nullable<_>('\u2593'),
                                             ProgressBarOnBottom = true,
                                             CollapseWhenFinished = false)
```

**Comment by Nekromancer** [comment]
I got the same problem on Windows Server 2016, but on local machine (newest Win 10) it's working fine

**Comment by dazinator** [comment]
I have found the same problem.

**Comment by dazinator** [comment]
.. and  if it helps this is my powershell version:

> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  251

**Comment by domn1995** [comment]
I'm having the same issue as well. I'm using four children progress bars.

**Comment by alkondrashov** [comment]
The same on my side

Windows 10 (powershell) and MacOS High Sierra (bash)

**Comment by dlech** [comment]
PR #28 should fix this (as a side effect).

**Comment by dlech** [comment]
FYI, there is a nuget package for testing here: https://github.com/dlech/shellprogressbar/releases/tag/4.0.1-dlech1

**Comment by Mpdreamz** [comment]
This should now work as per https://www.nuget.org/packages/ShellProgressBar/4.1.1 and @dlech fixes 😄
