### ISSUE TITLE
Change colour during progress

### ISSUE THREAD

**Issue by GuerrillaCoder** [Mpdreamz/shellprogressbar#21]
Is there anyway to change the colour after progressbar is initiated?  Would be cool to shift colours based on status of the task.

**Comment by Atulin** [comment]
Something like an array of colors added to options would be cool. Something like
```CS
Dictionary<double, ConsoleColor> colors = new Dictionary<double, ConsoleColor>
{
    {0.0, ConsoleColor.Red},
    {0.25, ConsoleColor.Yellow},
    {0.5, ConsoleColor.Green},
    {0.75, ConsoleColor.Cyan},
    {1.0, ConsoleColor.White}
};
```

**Comment by ransagy** [comment]
Definitely something i wanted to do just now - I wrote a little app to schedule CI/CD builds and report progress. When builds fail, i wanted to change their color.

Maybe make the color properties delegates that can decide colors on the fly? Shouldn't hurt performance as long as people don't do crazy things in them.

**Comment by marius-stanescu** [comment]
Yes, this would be nice. Any updates on this?

**Comment by Mpdreamz** [comment]
Took some time but this will go in to the next release 

https://github.com/Mpdreamz/shellprogressbar/pull/58

![pbar-changecolor](https://user-images.githubusercontent.com/245275/75098680-83658280-55b9-11ea-9de0-221912047199.gif)

Thanks for the suggestion 😄
