### ISSUE TITLE
High Tick Count performance Issues

### ISSUE THREAD

**Issue by xaruka** [Mpdreamz/shellprogressbar#25]
When using a high amount for max ticks (i.e. 10k), the ticking itself requires a lot of cpu. The following code requires 40+ seconds on my machine even though its not really doing anything:
```csharp
var progressBarOptions = new ProgressBarOptions()
{
    ProgressCharacter = '_'
};

using (var pbar = new ProgressBar(10000, "Test", progressBarOptions))
{
    for (var i = 0; i < pbar.MaxTicks; i++)
    {
        pbar.Tick();
    }
}
```

I didnt do any profiling but I assume its because of the redraw that occurs everytime ProgressBar.Tick() is called.

Since the realtime rendering uses a timer to update the rendering, i think it should be easily possible to implement. Maybe via an additional progress bar option or parameter to the progressbar constructor/tick function to disable redraw on tick - this would either require public access to the DisplayProgress method or it would force the use of the realtime update option.

**Comment by dlech** [comment]
What OS/.NET runtime are you using? I have found that performance on .NETCoreApp 2.1.2 on Linux x64 is so terrible, that the demo program here only updates about every 3 seconds after it has been running for a while. I've done some profiling and I think that it boils down to the locking used in the System.Console class is really bad and causes lots of spinlock waiting.

In researching this issue, I've noticed that there have been quite a few issues with locks on Linux causing performance issues in the dotnet/coreclr repository.

Maybe a possible solution here is to somehow get all calls to Console.* on a single thread. For example, we could make some kind of simple event loop that uses System.Collections.ConcurrentQueue for events.

**Comment by dlech** [comment]
It looks like the locking issues were just a problem in .NET Core 2.0 and were pretty much fixed in 2.1. There are still System.Console performance issue on .NET Core 2.1 unix platforms, but that is not really relevant to this issue.

Anyway, I've made a PR that addresses this issue.

**Comment by dlech** [comment]
FYI, there is a nuget package for testing here: https://github.com/dlech/shellprogressbar/releases/tag/4.0.1-dlech1

**Comment by Nihlus** [comment]
@dlech Have you considered uploading that package as an alternative on NuGet or MyGet? The official package suffers from a lot of issues that you have resolved.

**Comment by Mpdreamz** [comment]
Will have a look tomorrow @dlech :+1:

**Comment by Mpdreamz** [comment]
There is an option to not use the timer at all as well see `DisplayTimeInRealTime  = false`

https://github.com/Mpdreamz/shellprogressbar/blob/master/src/ShellProgressBar/ProgressBarOptions.cs#L29-L34

This works well especially if you have a high and frequently updating tick count.

**Comment by Nihlus** [comment]
Super, thanks both of you :D
