### ISSUE TITLE
Progress Bars take up more than one line

### ISSUE THREAD

**Issue by mandreko** [Mpdreamz/shellprogressbar#3]
I've been trying to diagnose this, but haven't yet figured it out. When I use the progress bars, it seems like every tick of the timer results in a new level of the progress bar. 

![Imgur](http://i.imgur.com/cD6QPmF.png)

**Comment by Mpdreamz** [comment]
Better late then never I hope but this is now part fixed in https://github.com/Mpdreamz/shellprogressbar/releases/tag/1.2.0
