### ISSUE TITLE
net4x as a target framework

### ISSUE THREAD

**Issue by Nekromancer** [Mpdreamz/shellprogressbar#30]
Hi,

Did you consider setting net4x framework as target framework? I know that netstandard is working well on everything, but when using "old csproj type" adding netstandard nuget results in additional dlls in binary directory. Binaries that are not really nessesary when targeting only .net 4.7 (for example).

It's not really a big issue, but it's kinda annoying. And i can't use new csproj for now (company legacy policy...)

**Comment by Mpdreamz** [comment]
I *think* `netstandard2.0` acts better in this regards. I can ship with both `netstandard1.3` and `netstandard2.0` TFM's in the nuget package

**Comment by Mpdreamz** [comment]
Enough time has passed and I don't want to support a separate `net4x` target. 

We now ship `netstandard2.0` which should act better and not polute `bin` as much.

Hope this helps @Nekromancer 👍
