### ISSUE TITLE
[Suggestion] Add a way to continue displaying text under the progressbar

### ISSUE THREAD

**Issue by Atulin** [Mpdreamz/shellprogressbar#31]
Sometimes I'd like to be more verbose about what the program does, doing something like

```
50.0% parsing done		      						00:10:07
===============================================---------------------------------------------
Parsing file 'hello world.txt'...
Done in 1.07s
Parsing file 'adasfadaad.txt'...
Done in 8.28s
Parsing file 'bank account passwords.txt'...
Done in 0.72s
```
Is there any changce it could be implemented? Even if not through ``Console.WriteLine("msg")``, then at least via something like ``pbar.Write("msg")``

**Comment by Kruno313** [comment]
I need it to.
The text color in that case should not be changed with Options.ForegroundColor as the color of the bar itself.

**Comment by rezunalex** [comment]
would love to have this too.

**Comment by Kruno313** [comment]
> would love to have this too.
I finally made my own for that reason: https://github.com/Kruno313/ConsoleProgressBar
It is also able to overwrite the Bar line with some text on the end.

**Comment by Atulin** [comment]
Nice! Maybe you could submit a pull request if it's not too hard?

**Comment by Kruno313** [comment]
My code is far from this, not an fork. I reused some concepts (Options f.i.), but wrote it new and it defferes to much. It also lacks some functionalities of this (shellprogressbar).
That's why I decided to make own project.

**Comment by Mpdreamz** [comment]
I've implemented `pbar.WriteLine("");` as a means to persist messages above the currently running console. 

This also plays nice when redirecting output to e.g a text file.

![Peek 2019-08-20 15-42](https://user-images.githubusercontent.com/245275/63352538-988afb80-c361-11e9-87c7-d56ff055cb61.gif)
