### ISSUE TITLE
On Linux  I always gets pbar.CompletedHandle.WaitOne(wait) false

### ISSUE THREAD

**Issue by srsaggam** [Mpdreamz/shellprogressbar#43]
if (!pbar.CompletedHandle.WaitOne(wait))
                    --->    Console.Error.WriteLine($"{nameof(FixedDurationBar)} did not signal {nameof(FixedDurationBar.CompletedHandle)} after {wait}");

**Comment by Mpdreamz** [comment]
What .NET core version are you on?

**Comment by Mpdreamz** [comment]
Closing this as linux is my main OS to develop on and I have not been able to reproduce this.
