### ISSUE TITLE
Running time can't exceed 24 hours

### ISSUE THREAD

**Issue by YingcaiDong** [Mpdreamz/shellprogressbar#45]
The running time will reset to 0 when the total running time exceeds 24 hours. I left a program runs for straight two days, I checked the progress by the end of the first day, and it shows 21:04:30. Later when I check the time again on the third day morning, it only shows 9 hours something.

So I am assuming that the timer resets.

**Comment by dlech** [comment]
Also see #40

**Comment by Mpdreamz** [comment]
#40 is now merged, thanks for reporting.
