### ISSUE TITLE
Timer broken in new Windows Terminal

### ISSUE THREAD

**Issue by enorfelt** [Mpdreamz/shellprogressbar#53]
In the new [Windows Terminal](https://github.com/microsoft/terminal).
When you start a new timer at the bottom of the terminal like this:
![image](https://user-images.githubusercontent.com/8871328/68597662-a605dc80-049d-11ea-8a1e-a68111db369a.png)

Each .Tick() breaks the progress bar up in multiple lines like this:
![image](https://user-images.githubusercontent.com/8871328/68597614-91c1df80-049d-11ea-883f-c1247ae72848.png)

Repro steps
1. Open a new "Windows terminal"
2. Make sure you are at the bottom of the terminal
3. Start a new progressbar

Expected
I dont want the progressbar to be broken in several lines.

Actual
The progressbar is broken up in several lines for each tick()

OBS
I get the same behavioure in a terminal in VS Code

**Comment by timmkrause** [comment]
Also having this issue.

**Comment by DurtyFree** [comment]
Sadly I have also this issue with Cmder Window Terminal

**Comment by Mpdreamz** [comment]
This should now be fixed with #57 

Keep an eye out for the next release and please comment here if it's not fixed. Closing this eagerly but will reopen if its still an issue.

Thanks for reporting!
