### ISSUE TITLE
Indeterminate Progress Bar Support

### ISSUE THREAD

**Issue by adam8797** [Mpdreamz/shellprogressbar#62]
An important feature of progress bars is that they have an indeterminate mode, for situations when we want to convey to the user that we're still working, but we have no idea what the progress of the action is.

Is this something that could be added?

**Comment by 0xced** [comment]
There's an excellent library that handle indeterminate progress reporting for .NET Standard: [Kurukuru](https://github.com/mayuki/Kurukuru). It's well documented, well architected and has a wide range of predefined spinner styles.

**Comment by peter-shinydocs** [comment]
Or you could just have an option to not display the percentage.

**Comment by Mpdreamz** [comment]
Implemented as per #74 thanks to @peter-shinydocs https://github.com/Mpdreamz/shellprogressbar/pull/74
