### ISSUE TITLE
Feature request: Set progress by percentage

### ISSUE THREAD

**Issue by KoalaBear84** [Mpdreamz/shellprogressbar#65]
I would like to set the progress by percentage.

Something like this:
```csharp
// Set progress to 10.7%
ProgressBar.SetPercentage(10.7);
// or
ProgressBar.SetPercentage(10.7m);
```

Currently using hardcoded 1000 ticks and:

```csharp
ProgressBar.Tick((int)(progress / 0.1m));
```

Also would be nice to support a single digits after the comma separator, so it will display "10.7%" instead of "10.70%". Also because it's faster to read, and not as 

Thanks!

**Comment by 0xced** [comment]
You can already achieve this by using `AsProgress<float>()` which returns an `IProgress<float>` that you can use to report progression as percentage:

```csharp
using var progressBar = new ProgressBar(10000, "My Progress Message");
var progress = progressBar.AsProgress<float>();
progress.Report(0.107); // 10.7%
```

**Comment by KoalaBear84** [comment]
Thanks, if this could be added to the readme it would be nice.
