### ISSUE TITLE
Readme drift

### ISSUE THREAD

**Issue by dpsutton** [Mpdreamz/shellprogressbar#7]
Hi there. Just grabbed your progress bar and I'm digging it. I noticed that you have a 4 argument constructor in the README showing a quick way to get up and running, but you have actually removed this overload and switched to the options style. Just wondering if you could add this to the readme for quick and easy up and running. Thanks and very much appreciate the progress bar.

**Comment by Mpdreamz** [comment]
@dpsutton thanks for this issue, i've been putting my head down the sand here for too long. Will get these updated soon!

**Comment by dpsutton** [comment]
Thanks. it wasn't a major issue at all, just an easy way to remove entry friction. The shellprogressbar was extremely nice to use. thanks very much!

**Comment by Mpdreamz** [comment]
Updated the readme today!
