### ISSUE TITLE
[FEATURE] Displaying ETA ?

### ISSUE THREAD

**Issue by beppe9000** [Mpdreamz/shellprogressbar#8]
I think that an option to display the estimate of ending time could be useful in many situations. 
It could be implemented with a stopwatch measuring the time between each `ProgressBar.Update` 
 call to get the average time of a cycle (which is then multiplied according to what we want to show). This allows for multiple time display modes: `elapsed/estimated total` or  `estimated remaining time` or anything else.

**Comment by Mpdreamz** [comment]
Great suggestion, will look into adding this in 👍

**Comment by Mpdreamz** [comment]
https://github.com/Mpdreamz/shellprogressbar/pull/38

Will allow you to provide this externally. I think this suffices for now, happy to take PR's for something more automagically 😄
