### ISSUE TITLE
Support to Int64 values of newTickCount and maxTicks

### ISSUE THREAD

**Issue by mauroao** [Mpdreamz/shellprogressbar#83]
I need to proccess billions of records and show progress, so a sugest change parameters  `newTickCount`, and `maxTicks`  to **Int64** intead of **Int**: 

```
public void Tick(int newTickCount, TimeSpan estimatedDuration, string message = null);
public void Tick(int newTickCount, string message = null);
protected ProgressBarBase(int maxTicks, string message, ProgressBarOptions options);
```

**Comment by Mpdreamz** [comment]
Hey @mauroao I would recommend not `Tick()`ing on every record in this case and only `Tick()` every 10k or 100k records.
