### ISSUE TITLE
No progress bar (text only) when running in PowerShell

### ISSUE THREAD

**Issue by benjamincburns** [Mpdreamz/shellprogressbar#9]
When running an application which uses ShellProgressBar in PowerShell, the text and elapsed time are rendered, but the progress bar itself is not.

![progress_bar_sshot](https://cloud.githubusercontent.com/assets/803016/18429191/4e1440ee-7926-11e6-8ac2-6ea66099b320.png)

**Comment by codejnki** [comment]
There's a couple of bug in the `ProgressBar.cs` in `DisplayProgress()` and `DrawChildren()` methods.  In [PR 12](https://github.com/Mpdreamz/shellprogressbar/pull/12) I've got this fixed.

**Comment by Mpdreamz** [comment]
This is now released in `4.0.0` https://github.com/Mpdreamz/shellprogressbar/blob/master/README.md#styling-changes

**Comment by bojanrajkovic** [comment]
I'm still seeing this--copied the code pretty much exactly from the example, and like the OP, I get the text and elapsed time, but no progress bar. If I set progress bar on the bottom then I get a progress bar, but no text/elapsed time.
